"""empty message

Revision ID: 0ac57077b6c7
Revises: da23820324b5
Create Date: 2021-06-25 06:58:02.870878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac57077b6c7'
down_revision = 'da23820324b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_column('test_field')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_field', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
