"""empty message

Revision ID: 3e3aa6fef41d
Revises: 8494953007ca
Create Date: 2021-06-25 07:27:41.541667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e3aa6fef41d'
down_revision = '8494953007ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_column('test_field')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_field', sa.VARCHAR(length=10), server_default=sa.text("'Testing'"), nullable=False))

    # ### end Alembic commands ###
