"""empty message

Revision ID: 5580b8259e0e
Revises: e18514cfef47
Create Date: 2021-06-25 06:45:56.027760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5580b8259e0e'
down_revision = 'e18514cfef47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_posts', 'test_field')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('test_field', sa.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
