"""empty message

Revision ID: 8494953007ca
Revises: 0ac57077b6c7
Create Date: 2021-06-25 06:59:27.629934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8494953007ca'
down_revision = '0ac57077b6c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_field', sa.String(length=10), server_default='Testing', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_column('test_field')

    # ### end Alembic commands ###
