"""empty message

Revision ID: e18514cfef47
Revises: 79cd3d4b29fd
Create Date: 2021-06-24 18:54:47.798879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e18514cfef47'
down_revision = '79cd3d4b29fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_posts', 'test_field')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('test_field', sa.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
